In [9]:
import pandas as pd
from functools import reduce

In [19]:
data_2015 = pd.read_csv('2015.csv')
data_2015.rename(columns={'Happiness Score':'Happiness Score'},inplace=True)
data_2015 = pd.DataFrame(data =[data_2015['Country'],data_2015['Happiness Score']]).transpose()

data_2016 = pd.read_csv('2016.csv')
data_2016.rename(columns={'Happiness.Score':'Happiness Score'},inplace=True)
data_2016 = pd.DataFrame(data =[data_2016['Country'],data_2016['Happiness Score']]).transpose()

data_2017 = pd.read_csv('2017.csv')
data_2017.rename(columns={'Happiness.Score':'Happiness Score'},inplace=True)
data_2017.replace('Hong Kong S.A.R., China','Hong Kong',inplace=True)
data_2017 = pd.DataFrame(data =[data_2017['Country'],data_2017['Happiness Score']]).transpose()

data_2018 = pd.read_csv('2018.csv')
data_2018.rename(columns={'Score':'Happiness Score','Country or region':'Country'},inplace=True)
data_2018.replace('Northern Cyprus','North Cyprus',inplace=True)
data_2018 = pd.DataFrame(data =[data_2018['Country'],data_2018['Happiness Score']]).transpose()

data_2019 = pd.read_csv('2019.csv')
data_2019.rename(columns={'Score':'Happiness Score','Country or region':'Country'},inplace=True)
data_2019.replace('Northern Cyprus','North Cyprus',inplace=True)
data_2019.replace('North Macedonia','Macedonia',inplace=True)
data_2019 = pd.DataFrame(data =[data_2019['Country'],data_2019['Happiness Score']]).transpose()

data_2020 = pd.read_csv('2020.csv')
data_2020.rename(columns={'Ladder score':'Happiness Score','Country name':'Country'},inplace=True)
data_2020.replace('Hong Kong S.A.R. of China','Hong Kong',inplace=True)
data_2020.replace('Northern Cyprus','North Cyprus',inplace=True)
data_2020.replace('North Macedonia','Macedonia',inplace=True)
data_2020 = pd.DataFrame(data =[data_2020['Country'],data_2020['Happiness Score']]).transpose()

In [30]:
data = pd.concat([data_2015,data_2016,data_2017,data_2018,data_2019,data_2020],join='outer')
data.groupby(['Country'])
data

                      Country Happiness Score
0                 Switzerland           7.587
1                     Iceland           7.561
2                     Denmark           7.527
3                      Norway           7.522
4                      Canada           7.427
..                        ...             ...
148  Central African Republic          3.4759
149                    Rwanda          3.3123
150                  Zimbabwe          3.2992
151               South Sudan          2.8166
152               Afghanistan          2.5669

[935 rows x 2 columns]